In [1]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np

def pprint(arr):
    print(f'type: {type(arr)}')
    print(f'shape: {arr.shape}, dimension: {arr.ndim}, dtype: {arr.dtype}')
    print('numpy 배열의 데이터\n', arr, sep='')

numpy 파일 입출력

numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일로 저장하고 불러오는 기능을 제공한다.

In [44]:
a = np.random.randint(1, 11, (2, 3))
print(a)
b = np.random.randint(1, 11, (2, 3))
print(b)

[[4 5 6]
 [4 9 3]]
[[ 5  8 10]
 [ 8  7  3]]


save(), savez() 메소드로 numpy 배열 객체를 바이너리 형태의 파일로 저장할 수 있다.  
save() 메소드는 numpy 배열 1개를 저장한다. 확장명 => *.npy  
savez() 메소드는 numpy 배열 여러개를 저장한다. 확장명 => *.npz  

In [46]:
# a라는 numpy 배열을 바이너리 형태로 저장한다.
# save('경로', 배열명)
np.save('./output/my_array1', a)

# a, b 배열을 바이너리 형태로 저장한다.
# savez('경로', 배열명1, 배열명2, ...)
np.savez('./output/my_array2', a, b)

load() 메소드로 npy, npz 파일에서 데이터를 읽어올 수 있다.  
save(), savez() 메소드는 메소드에 따라 정해진 확장명이 있으므로 확장명을 입력하지 않아도 되지만 load() 메소드는 반드시 확장명까지 입력해야 한다.  
load('경로')

In [57]:
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))
print('=' * 100)

# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFile = np.load('./output/my_array2.npz')
print(npzFile['arr_0'])
print(npzFile['arr_1'])
print('=' * 100)

for arr in npzFile:
    print(arr)
    print(npzFile[arr])

[[4 5 6]
 [4 9 3]]
NpzFile './output/my_array2.npz' with keys: arr_0, arr_1
[[4 5 6]
 [4 9 3]]
[[ 5  8 10]
 [ 8  7  3]]
arr_0
[[4 5 6]
 [4 9 3]]
arr_1
[[ 5  8 10]
 [ 8  7  3]]


savetxt() 메소드로 numpy 배열 객체를 텍스트 형태의 파일로 저장할 수 있다.  
여기서 말하는 텍스트 파일은 확장명이 txt인 파일을 말하는 것이 아니고 csv 또는 tsv 파일을 의미한다.  
savetxt('경로', 배열명, delimiter='구분자') 구분자를 생략하면 공백이 구분자로 사용된다.

In [60]:
np.savetxt('./output/saved.csv', a, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved.tsv', a, delimiter='\t') # tsv 파일은 데이터를 tab('\t')으로 구분한다.

배열 연산

In [65]:
# reshape() 메소드는 numpy 배열의 차원(shape)을 변경한다.
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int64
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int64
numpy 배열의 데이터
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [67]:
# 덧셈 
print(np.add(a, b))
print(a + b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [69]:
# 뺄셈
print(np.subtract(a, b))
print(a - b)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [71]:
# 곱셈
print(np.multiply(a, b))
print(a * b)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [73]:
# 나눗셈
print(np.divide(a, b))
print(a / b)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [77]:
# 정수 나눗셈: //(몫), %(나머지), divmod()
print(a // b)
print(a % b)
print(np.divmod(a, b)) # divmod() 메소드는 몫과 나머지를 계산한다.
print(np.divmod(a, b)[0]) # 몫
print(np.divmod(a, b)[1]) # 나머지

[[0 0 0]
 [0 1 1]
 [2 4 9]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]
(array([[0, 0, 0],
       [0, 1, 1],
       [2, 4, 9]]), array([[1, 2, 3],
       [4, 0, 2],
       [1, 0, 0]]))
[[0 0 0]
 [0 1 1]
 [2 4 9]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]


In [79]:
# 지수
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [80]:
# 제곱근
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [82]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [84]:
# 로그
print(np.log(a))
print(np.log10(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [87]:
# 행렬의 내적
print(np.dot(a, b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<img src="dot.png" width="800" align="left" />

In [88]:
# 배열 요소별 비교: >, >=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [90]:
# array_equal() 메소드로 배열 전체를 비교할 수 있다.
print(np.array_equal(a, b))

False


배열 집계

numpy의 모든 배열 집계를 수행하는 메소드는 axis(축)를 기준으로 계산하며 axis를 지정하지 않으면 None이 기본값으로 사용된다.

In [92]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


합계: 넘파이배열.sum(), np.sum(넘파이배열)

In [100]:
# axis를 생략하면 None이 기본값으로 사용되서 axis=None를 입력한 것과 같은 기능이 실행된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


<img src="numpyImage02.jpg" width="200" align="left" />

In [98]:
# axis=0은 각 행의 동일한 열 인덱스 요소를 그룹으로 계산한다. => 각 열의 합계
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


<img src="numpyImage03.jpg" width="200" align="left" />

In [99]:
# axis=1은 각 열의 동일한 행 인덱스 요소를 그룹으로 계산한다. => 각 행의 합계
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


<img src="numpyImage04.jpg" width="200" align="left" />

최대값: 넘파이배열.max(), np.max(넘파이배열)  
최소값: 넘파이배열.min(), np.min(넘파이배열)

In [104]:
print(a.max()) # print(a.max(axis=None))
print(np.max(a)) # print(np.max(a, axis=None))
print(a.min()) # print(a.min(axis=None))
print(np.min(a)) # print(np.min(a, axis=None))

9
9
1
1


In [106]:
print(a.max(axis=0)) # print(np.max(a, axis=0))
print(a.min(axis=0)) # print(np.min(a, axis=0))

[7 8 9]
[1 2 3]


In [108]:
print(a.max(axis=1)) # print(np.max(a, axis=1))
print(a.min(axis=1)) # print(np.min(a, axis=1))

[3 6 9]
[1 4 7]


누적합계: 넘파이배열.cumsum(), np.cumsum(넘파이배열)

In [111]:
print(a.cumsum()) # print(a.cumsum(axis=None))
print(np.cumsum(a)) # print(np.cumsum(a, axis=None))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [112]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [113]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균: 넘파이배열.mean(), np.mean(넘파이배열)

In [114]:
print(a.mean()) # print(a.mean(axis=None))
print(np.mean(a)) # print(np.mean(a, axis=None))

5.0
5.0


In [115]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

[4. 5. 6.]
[4. 5. 6.]


In [116]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

[2. 5. 8.]
[2. 5. 8.]


중위수는 데이터를 정렬한 결과에서 정 가운데 위치하는 수를 의미한다.  
중위수는 데이터의 개수에 따라 계산하는 방법이 다르다. 홀수개면 (n + 1) / 2 번째 값이 중위수이고 짝수개면 n / 2 번째 값과 n / 2 + 1 번째 값의 평균이 중위수이다.
np.median(넘파이배열)

In [122]:
print(np.median(a)) # print(np.median(a, axis=None))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


상관계수: np.corrcoef(배열이름)

In [125]:
# 전체 데이터를 대상으로만 작업이 가능하다.
print(np.corrcoef(a))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


분산: 넘파이배열.var(), np.var(넘파이배열)

In [128]:
print(a.var()) # print(a.var(axis=None))
print(np.var(a)) # print(np.var(a, axis=None))

6.666666666666667
6.666666666666667


In [130]:
print(a.var(axis=0))
print(np.var(a, axis=0)) 

[6. 6. 6.]
[6. 6. 6.]


In [131]:
print(a.var(axis=1))
print(np.var(a, axis=1)) 

[0.66666667 0.66666667 0.66666667]
[0.66666667 0.66666667 0.66666667]


표준편차: 넘파이배열.std(), np.std(넘파이배열)

In [132]:
print(a.std()) # print(a.std(axis=None))
print(np.std(a)) # print(np.std(a, axis=None))

2.581988897471611
2.581988897471611


In [133]:
print(a.std(axis=0))
print(np.std(a, axis=0)) 

[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]


In [134]:
print(a.std(axis=1))
print(np.std(a, axis=1)) 

[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]


브로드캐스팅

shape이 같은 두 배열의 이항 연산은 같은 배열 요소별로 연산이 실행된다.  
두 배열의 shape이 다를 경우 두 배열간의 형상(모양)을 맞추는 아래 그림과 같은 브로드캐스팅 과정을 거쳐 실행된다.

<img src="numpyImage05.jpg" width="900" align="left" />

shape이 같은 두 배열의 연산

In [136]:
a = np.arange(1, 25).reshape(4, 6)
print(a)
b = np.arange(25, 49).reshape(4, 6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [137]:
# shape이 같은 배열을 이항 연산할 경우 위치가 같은 요소 단위로 실행된다.
print(a + b)

[[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


shape이 다른 두 배열의 연산

shape이 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생시 두 배열을 같은 shape으로 만든 후 연산을 실행한다.

In [139]:
# 배열과 스칼라(단일값)의 연산
# 배열과 스칼라 사이의 이항 연산시 스칼라를 배열로 변환한다.
print(a)
print(a + 100)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [141]:
# a + 100은 다음과 같은 과정을 거쳐서 실행된다.
new_arr = np.full_like(a, fill_value=100)
print(new_arr)
print(a + new_arr)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [143]:
# shape이 다른 배열의 연산
a = np.arange(5).reshape(1, 5)
print(a)
b = np.arange(5).reshape(5, 1)
print(b)
print(a + b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


numpy는 벡터 연산을 지원한다.  
numpy는 벡터화 기능이 적용되어 있어서 벡터 연산을 적용할 경우 처리 속도가 100배 이상 빠르다.

In [144]:
a = np.arange(1, 10000001)
print(a)

[       1        2        3 ...  9999998  9999999 10000000]


In [146]:
%%time
result = 0
for i in a:
    result += i
print(result)

50000005000000
CPU times: total: 1.81 s
Wall time: 1.79 s


In [147]:
%%time
result = np.sum(a)
print(result)

50000005000000
CPU times: total: 0 ns
Wall time: 9.56 ms


배열 복사

numpy 배열 객체에 대한 인덱싱, 슬라이싱이 반환하는 numpy 배열은 새로은 객체가 아닌 기존 배열의 view이다.  
반환된 배열의 값을 변경하면 원본 배열에 변경한 값이 반영된다. => 얕은 복사(주소 복사)

In [156]:
a = np.random.randint(0, 9, (3, 3))
print(a)
b = a[0] # b에는 a배열의 0번째 인덱스에 해당된 데이터가 저장된 주소가 전달된다.
print(b)
b[1] = 777 # a[0]와 b는 같은 주소를 기억하기때문에 b[1]를 수정하면 a[0][1]도 같이 수정된다.
print(b)
print(a)

[[2 7 7]
 [6 5 4]
 [7 4 2]]
[2 7 7]
[  2 777   7]
[[  2 777   7]
 [  6   5   4]
 [  7   4   2]]


In [157]:
a = np.random.randint(0, 9, (3, 3))
print(a)
b = a[:, 0] # 행은 상관없이(전체행) 0번째 열만 슬라이싱 한다. 한 열 인덱싱
print(b)
b[1] = 777
print(b)
print(a)

[[7 4 7]
 [0 2 8]
 [3 6 6]]
[7 0 3]
[  7 777   3]
[[  7   4   7]
 [777   2   8]
 [  3   6   6]]


기존 배열로부터 새로운 배열을 생성하기 위해 copy() 메소드를 사용한다.  
copy() 메소드로 복사된 배열은 원본 배열과 완전히 다른 별도의 객체가 된다. => 깊은 복사  
넘파이배열.copy(), np.copy(넘파이배열)

In [158]:
a = np.random.randint(0, 9, (3, 3))
print(a)
# b = a[0] # 얕은 복사
b = a.copy()[0] # 깊은 복사
print(b)
b[1] = 777
print(b)
print(a)

[[1 3 7]
 [2 3 2]
 [5 4 7]]
[1 3 7]
[  1 777   7]
[[1 3 7]
 [2 3 2]
 [5 4 7]]


In [159]:
a = np.random.randint(0, 9, (3, 3))
print(a)
# b = a[:, 0] # 얕은 복사
b = np.copy(a)[:, 0] # 깊은 복사
print(b)
b[1] = 777
print(b)
print(a)

[[4 0 2]
 [8 1 4]
 [0 5 8]]
[4 8 0]
[  4 777   0]
[[4 0 2]
 [8 1 4]
 [0 5 8]]


배열 정렬

numpy는 axis를 기준으로 요소들을 정렬하는 sort() 메소드를 제공한다.  
넘파이배열.sort(), np.sort(넘파이배열)  
sort() 메소드의 axis를 생략했을때 기본값은 None이 아닌 -1이다. -1은 넘파이 배열의 마지막 axis를 의미한다.  
아래 a 배열은 2차원 배열이므로 axis가 0과 1이 존재하고 이때, 마지막 axis는 1이다.

In [160]:
a = np.random.randint(1, 101, (3, 3))
print(a)

[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]


In [166]:
b = a.copy() # 정렬 작업을 위해 깊은 복사로 복사본을 만든다.
print(b)
# 넘파이배열.sort() 형식으로 sort() 메소드를 실행하면 정렬 결과가 리턴되는 것이 아니고 넘파이 배열에 즉시(바로) 반영된다.
c = b.sort() # b.sort(axis=-1) => 기본값, b.sort(axis=1) => 마지막 2차원 배열의 axis
print(c)
print(b)

[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]
None
[[  6  29  52]
 [  3   6  75]
 [ 17  71 100]]


In [167]:
b = a.copy()
print(b)
c = b.sort(axis=0)
print(c)
print(b)

[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]
None
[[  3   6   6]
 [ 52  17  75]
 [ 71  29 100]]


In [168]:
b = a.copy()
print(b)
# np.sort(넘파이배열) 형식으로 sort() 메소드를 실행하면 정렬 결과를 리턴하고 원본은 변형되지 않는다.
c = np.sort(b) # np.sort(b, axis=-1), np.sort(b, axis=1)
print(c)
print(b)

[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]
[[  6  29  52]
 [  3   6  75]
 [ 17  71 100]]
[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]


In [190]:
b = a.copy()
print(b)
c = np.sort(b, axis=0)
print(c)
print(b)

[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]
[[  3   6   6]
 [ 52  17  75]
 [ 71  29 100]]
[[ 52  29   6]
 [  3   6  75]
 [ 71  17 100]]
