In [1]:
import warnings
warnings.filterwarnings("ignore")
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np


Instructions for updating:
non-resource variables are not supported in the long term


<img src="./multilayer_perceptron1.png" wigth="1400" align="left" />

<img src="./multilayer_perceptron2.png" wigth="1400" align="left" />

<img src="./multilayer_perceptron3.png" wigth="1400" align="left" />

<img src="./multilayer_perceptron4.png" wigth="1400" align="left" />

xor 연산은 입력 데이터를 X라고 할 경우 `[[0, 0], [0, 1], [1, 0], [1, 1]]`과 같은 경우의 수가 있다.  
총 4개의 입력 데이터가 각각 2개의 피쳐를 가지고 있으므로 X는 `[4, 2]`의 형태로 정의할 수 있다.  
입력값에 따른 레이블 Y는 `[[0], [1], [1], [0]]`이므로 Y는 `[4, 1]`의 형태로 정의할 수 있다.

In [2]:
X = tf.placeholder(dtype=tf.float32, shape=[4, 2]) # 피쳐
Y = tf.placeholder(dtype=tf.float32, shape=[4, 1]) # 레이블

1번째 히든 레이어에서 2개의 입력(X)과 1개의 바이어스(B1)을 받아서 2개의 시그모이드 함수 출력(Z)을 2번째 히든 레이어로 전달한다.

2개의 X(x1, x2)와 바이어스(bias)를 입력으로 받는 2개의 뉴런을 만든다.

In [3]:
# 2개의 입력을 받는 2개의 뉴런을 사용하기 위해서 가중치를 [입력 데이터의 개수, 뉴런의 개수] 만큼의 가중치를 난수를 만든다.
W1 = tf.Variable(tf.random_normal([2, 2], dtype=tf.float32))
# 각 뉴런은 1개의 바이어스를 가진다.
# tensorflow의 zeros() 메소드는 모든 원소의 값이 0인 텐서(2차원 이상의 행렬)를 생성한다.
B1 = tf.Variable(tf.zeros([2]))
# 시그모이드 함수를 이용해서 1번째 히든 레이어의 출력을 리턴한다.
Z = tf.sigmoid(tf.matmul(X, W1) + B1)

In [4]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(W1))
print(sess.run(B1))
x_train = [[0, 0], [0, 1], [1, 0], [1, 1]]
print(sess.run(Z, feed_dict={X: x_train}))

[[-0.83360434  0.7562559 ]
 [ 0.8309359   1.4078399 ]]
[0. 0.]
[[0.5        0.5       ]
 [0.69655275 0.803425  ]
 [0.30288348 0.6805403 ]
 [0.49933288 0.8969787 ]]


2번째 히든 레이어에서 1번째 히든 레이어의 출력값(Z1)과 바이어스(B2)을 받아서 1개의 시그모이드 함수 결과(Y_hat) 출력한다.

2개의 Z(z1, z2)와 바이어스(bias)를 입력으로 받는 1개의 뉴런을 만든다.

In [5]:
W2 = tf.Variable(tf.random_normal([2, 1], dtype=tf.float32))
B2 = tf.Variable(tf.zeros([1]))
Y_hat = tf.sigmoid(tf.matmul(Z, W2) + B2)

In [6]:
sess.run(tf.global_variables_initializer())
print(sess.run(W2))
print(sess.run(B2))
print(sess.run(Y_hat, feed_dict={X: x_train}))

[[-1.3553058]
 [-0.6028829]]
[0.]
[[0.27307156]
 [0.2919614 ]
 [0.21326627]
 [0.21209075]]


손실 함수 크로스 엔트로피를 사용하고 경사 하강법으로 모델의 매개 변수(가중치, 바이어스)를 최적화 한다.

In [17]:
# 크로스 엔트로피
loss = tf.reduce_mean(
    -1 * (Y * tf.log(Y_hat) + (1.0 - Y) * tf.log(1.0 - Y_hat)) 
)

# 경사 하강법
train = tf.train.GradientDescentOptimizer(0.05).minimize(loss)

학습 시킨다.

In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

x_train = [[0, 0], [0, 1], [1, 0], [1, 1]] # 피쳐
y_train = [[0], [1], [1], [0]] # 레이블

for epoch in range(40001):
    sess.run(train, feed_dict={X: x_train, Y: y_train})
    if epoch % 5000 == 0:
        print('epoch: {}'.format(epoch))
        print('output\n', sess.run(Y_hat, feed_dict={X: x_train}), sep='')

epoch: 0
output
[[0.32467276]
 [0.39136356]
 [0.4481499 ]
 [0.45291442]]
epoch: 5000
output
[[0.071525 ]
 [0.7526949]
 [0.5844631]
 [0.6078552]]
epoch: 10000
output
[[0.04189277]
 [0.9307348 ]
 [0.9317006 ]
 [0.12824142]]
epoch: 15000
output
[[0.01957183]
 [0.9749279 ]
 [0.9753334 ]
 [0.04166109]]
epoch: 20000
output
[[0.01246587]
 [0.9851254 ]
 [0.9853413 ]
 [0.02377781]]
epoch: 25000
output
[[0.00909826]
 [0.98950475]
 [0.9896428 ]
 [0.01645542]]
epoch: 30000
output
[[0.00714795]
 [0.9919184 ]
 [0.99201614]
 [0.01252584]]
epoch: 35000
output
[[0.00588   ]
 [0.99344116]
 [0.99351513]
 [0.01008886]]
epoch: 40000
output
[[0.00499077]
 [0.99448687]
 [0.99454534]
 [0.00843483]]
