In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns

import sklearn
sklearn.set_config(display='text')
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from sklearn.naive_bayes import GaussianNB # 가우시안 나이브 베이즈 알고리즘을 사용하기 위해 import 한다.
# from sklearn.naive_bayes import BernoulliNB # 베르누이 나이브 베이즈 알고리즘을 사용하기 위해 import 한다.
# from sklearn.naive_bayes import MultinomialNB # 다항분포 베이즈 알고리즘을 사용하기 위해 import 한다.

나이브 베이즈(naive bayes)는 서로 조건부 독립(conditional independence)인 피쳐를 가정하고, 베이즈 이론을 기반으로 하는 머신러닝 알고리즘 이다.

$y$가 주어졌을 때 $x_1$과 $x_2$가 독립일 경우 아래의 식을 만족한다.

$$P(X_1, X_2|Y) = P(X_1|Y)P(X_2|Y)$$

와인 데이터를 사용해서 와인 종류를 분류하는 모델을 생성하고 학습시킨다.

In [6]:
# 데이터 불러오기
raw_data = datasets.load_wine() # 사이킷런 라이브러리가 제공하는 와인 데이터를 불러온다.
# print(raw_data)

# 피쳐, 레이블 데이터 저장
xData = raw_data.data # 피쳐 데이터를 저장한다.
yData = raw_data.target # 피쳐 데이터에 따른 레이블을 저장한다.
# print(xData.shape, yData.shape)

# 학습 데이터와 테스트 데이터로 분할
x_train, x_test, y_train, y_test = train_test_split(xData, yData, random_state=0)
# print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

# 데이터 표준화(정규화)
scaler = StandardScaler() # 표준화 스케일러 객체를 만든다.
x_train = scaler.fit_transform(x_train) # 학습 데이터를 표준화 스케일러로 표준화하고 적용한다.
x_test = scaler.transform(x_test) # 테스트 데이터를 학습 데이터로 표준화한 스케일러에 적용한다.

# 모델 생성 후 데이터 학습
model = GaussianNB().fit(x_train, y_train) # 가우시안 나이브 베이즈 모델을 만들고 학습시킨다.

학습된 모델로 테스트 데이터를 예측한다.

In [7]:
predict = model.predict(x_test) # predict() 메소드의 인수로 표준화된 테스트 데이터(x_test)를 넘겨서 가우시안 나이브 베이즈 모델을 예측한다.
print(predict)

[0 2 1 0 1 1 0 2 1 1 2 2 0 0 2 1 0 0 2 0 0 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [8]:
predict_proba = model.predict_proba(x_test) # predict_proba() 메소드의 인수로 표준화된 테스트 데이터(x_test)를 넘겨서 각 클래스에 속할 확률로 예측한다.
print(predict_proba)

[[9.99999998e-01 2.39855068e-09 3.93942190e-28]
 [1.02435837e-22 1.66051100e-26 1.00000000e+00]
 [7.92355012e-03 9.92076450e-01 5.95410457e-30]
 [1.00000000e+00 2.72260125e-10 3.34831578e-28]
 [4.35468158e-08 9.99999956e-01 3.69825238e-16]
 [5.08553299e-06 9.99994914e-01 2.31373732e-59]
 [1.00000000e+00 4.75547693e-10 3.64407326e-33]
 [1.96712277e-23 2.62334773e-13 1.00000000e+00]
 [2.73307354e-09 9.99999997e-01 1.10477876e-15]
 [8.68229871e-15 9.99999683e-01 3.17272768e-07]
 [8.55400548e-16 1.38690551e-05 9.99986131e-01]
 [8.44068243e-31 1.86713198e-09 9.99999998e-01]
 [1.00000000e+00 1.03618234e-17 6.34324046e-44]
 [5.61098607e-01 4.38901393e-01 8.24910606e-34]
 [7.67388743e-18 1.02061615e-17 1.00000000e+00]
 [2.03470333e-10 1.00000000e+00 3.53437663e-27]
 [9.99999392e-01 6.07622376e-07 8.23501136e-30]
 [1.00000000e+00 3.99552532e-26 2.07249426e-58]
 [6.56895194e-12 1.01217393e-01 8.98782607e-01]
 [1.00000000e+00 5.48306756e-11 3.35595874e-39]
 [8.48326406e-01 1.51673594e-01 4.891989

학습된 모델을 평가한다.

In [9]:
# 혼동 행렬
# confusion_matrix() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 혼동 행렬을 출력한다.
confusion = confusion_matrix(y_test, predict)
print(confusion)

[[16  0  0]
 [ 2 18  1]
 [ 0  0  8]]


In [10]:
# 분류 리포트
# classification_report() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 분류 리포트를 출력한다.
classification = classification_report(y_test, predict, target_names=raw_data.target_names)
print(classification)

              precision    recall  f1-score   support

     class_0       0.89      1.00      0.94        16
     class_1       1.00      0.86      0.92        21
     class_2       0.89      1.00      0.94         8

    accuracy                           0.93        45
   macro avg       0.93      0.95      0.94        45
weighted avg       0.94      0.93      0.93        45



In [11]:
# 정확도 평가
# accuracy_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 정확도를 계산한다.
accuracy = accuracy_score(y_test, predict)
print(accuracy)

0.9333333333333333


In [12]:
# 정밀도 평가
# precision_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 정밀도를 계산한다.
precision = precision_score(y_test, predict, average=None)
print(precision)

[0.88888889 1.         0.88888889]


In [13]:
# 재현율 평가
# recall_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 재현율을 계산한다.
recall = recall_score(y_test, predict, average=None)
print(recall)

[1.         0.85714286 1.        ]


In [14]:
# f1 score 평가
# f1_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 f1 score를 계산한다.
f1 = f1_score(y_test, predict, average=None)
print(f1)

[0.94117647 0.92307692 0.94117647]
