In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns

import sklearn
sklearn.set_config(display='text')
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from sklearn.ensemble import RandomForestClassifier # 랜덤 포레스트 알고리즘을 사용하기 위해 import 한다.

앙상블 학습은 크게 독립적 앙상블과 의존적 앙상블로 나눌 수 있다.

`독립적 앙상블(independent ensemble)`  
독립적 앙상블 방법에서 사용하는 개별 분류기들은 서로 독립적인 알고리즘이므로 각 분류기는 서로 다른 머신러닝 알고리즘을 사용할 수 있다. 각 분류기가 독립적이므로 효과적으로 병렬화 할 수 있는 장점이 있다.

`의존적 앙상블(dependent ensemble)`  
의존적 앙상블 방법은 독립적 앙상블 방법과는 달리 개별 학습기들이 서로 독립이 아닌 경우를 의미하며 의존적 앙상블 방법 중 가장 유명한 방법은 부스팅 이다.

배깅(bagging, Bootstrap AGGregatING)과 랜덤 포레스트(random forest)  

배깅은 개별 분류기들의 결과를 종합하여 최종 분류기의 성능을 향상시키는 방법이다.  
개별 분류기들이 동일한 학습 데이터로 학습하는 보팅과는 달리 배깅은 오리지널 학습 데이터셋에서 샘플(bootstrap)을 뽑아서 학습한다. 부트스트랩이란 중복을 허용한 랜덤 샘플링 방식을 의미하고 개별 분류 모델의 결과값을 모아서 다수결 투표를 통해서 최종 예측을 하게된다.  
랜덤 포레스트는 여려 개의 개별 분류기인 의사결정 트리를 토대로 예측한 결과를 종합해 전체 예측 정확도를 높이는 방법이다.

와인 데이터를 사용해서 와인 종류를 분류하는 모델을 생성하고 학습시킨다.

In [55]:
# 데이터 불러오기
raw_data = datasets.load_wine() # 사이킷런 라이브러리가 제공하는 와인 데이터를 불러온다.
# print(raw_data)

# 피쳐, 레이블 데이터 저장
xData = raw_data.data # 피쳐 데이터를 저장한다.
yData = raw_data.target # 피쳐 데이터에 따른 레이블을 저장한다.
# print(xData.shape, yData.shape)

# 학습 데이터와 테스트 데이터로 분할
x_train, x_test, y_train, y_test = train_test_split(xData, yData, random_state=0)
# print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

# 데이터 표준화(정규화)
scaler = StandardScaler() # 표준화 스케일러 객체를 만든다.
x_train = scaler.fit_transform(x_train) # 학습 데이터를 표준화 스케일러로 표준화하고 적용한다.
x_test = scaler.transform(x_test) # 테스트 데이터를 학습 데이터로 표준화한 스케일러에 적용한다.

# 모델 생성 후 데이터 학습
model = RandomForestClassifier(random_state=0, max_depth=3).fit(x_train, y_train) # 랜덤 포레스트 모델을 만들고 학습시킨다.

학습된 모델로 테스트 데이터를 예측한다.

In [56]:
predict = model.predict(x_test) # predict() 메소드의 인수로 표준화된 테스트 데이터(x_test)를 넘겨서 서포트 벡터 머신 모델을 예측한다.
print(predict)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [57]:
predict_proba = model.predict_proba(x_test) # predict_proba() 메소드의 인수로 표준화된 테스트 데이터(x_test)를 넘겨서 각 클래스에 속할 확률로 예측한다.
print(predict_proba)

[[0.96648677 0.02191666 0.01159657]
 [0.00803061 0.13210104 0.85986835]
 [0.25908403 0.71894594 0.02197003]
 [0.91275927 0.06686862 0.0203721 ]
 [0.11200941 0.7827148  0.10527579]
 [0.3969256  0.52087364 0.08220076]
 [0.91250886 0.05988635 0.02760478]
 [0.00704412 0.097031   0.89592488]
 [0.01367628 0.97522275 0.01110097]
 [0.020483   0.95695953 0.02255747]
 [0.15000557 0.15084747 0.69914696]
 [0.00347269 0.12989998 0.86662733]
 [0.97948677 0.01808333 0.0024299 ]
 [0.27908403 0.69894594 0.02197003]
 [0.02337269 0.06464707 0.91198023]
 [0.03019417 0.96288857 0.00691726]
 [0.87534568 0.08792046 0.03673386]
 [0.97948677 0.01808333 0.0024299 ]
 [0.0235357  0.39794663 0.57851767]
 [0.97537566 0.02219444 0.0024299 ]
 [0.45644253 0.48099515 0.06256232]
 [0.8299621  0.13313565 0.03690224]
 [0.56989761 0.34479756 0.08530484]
 [0.05314679 0.93069654 0.01615667]
 [0.01663471 0.69830437 0.28506092]
 [0.0290516  0.93777952 0.03316888]
 [0.23494735 0.65528833 0.10976432]
 [0.01229015 0.97640084 0.01

학습된 모델을 평가한다.

In [58]:
# 혼동 행렬
# confusion_matrix() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 혼동 행렬을 출력한다.
confusion = confusion_matrix(y_test, predict)
print(confusion)

[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


In [59]:
# 분류 리포트
# classification_report() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 분류 리포트를 출력한다.
classification = classification_report(y_test, predict, target_names=raw_data.target_names)
print(classification)

              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        16
     class_1       1.00      0.95      0.98        21
     class_2       0.89      1.00      0.94         8

    accuracy                           0.98        45
   macro avg       0.96      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [60]:
# 정확도 평가
# accuracy_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 정확도를 계산한다.
accuracy = accuracy_score(y_test, predict)
print(accuracy)

0.9777777777777777


In [61]:
# 정밀도 평가
# precision_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 정밀도를 계산한다.
precision = precision_score(y_test, predict, average=None)
print(precision)

[1.         1.         0.88888889]


In [62]:
# 재현율 평가
# recall_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 재현율을 계산한다.
recall = recall_score(y_test, predict, average=None)
print(recall)

[1.         0.95238095 1.        ]


In [63]:
# f1 score 평가
# f1_score() 함수의 인수로 테스트 데이터의 레이블(y_test)과 예측값(predict)을 순서대로 넘겨서 f1 score를 계산한다.
f1 = f1_score(y_test, predict, average=None)
print(f1)

[1.         0.97560976 0.94117647]
