In [1]:
import warnings
warnings.filterwarnings("ignore")
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np


Instructions for updating:
non-resource variables are not supported in the long term


<img src="./deepLearning1.png" wigth="1400" align="left" />

<img src="./deepLearning2.png" wigth="1400" align="left" />

<img src="./perceptron1.png" wigth="1400" align="left" />

<img src="./perceptron2.png" wigth="1400" align="left" />

<img src="./perceptron3.png" wigth="1400" align="left" />

퍼셉트론은 엄밀하게 말하면 딥러닝은 아니지만 뉴런과 상당히 닮은 분류기이다.  
뉴런의 계산 과정을 이해하고 뉴런 하나만으로 AND 연산 또는 OR 연산과 같은 기초적인 연산을 할 수 있음을 알아본다.

In [2]:
# 퍼셉트론 코드의 이해도를 높이기 위해 1을 True로 0을 False로 그리고 편향은 1로 지정한다.
T = 1.0
F = 0.0
B = 1.0

AND, OR, XOR 실습 데이터를 함수로 정의한다.

In [3]:
def and_data():
    # 학습 데이터
    X = [
        [F, F, B], # F
        [F, T, B], # F
        [T, F, B], # F
        [T, T, B], # T
    ]
    # 학습 데이터에 따른 실제값
    Y = [
        [F],
        [F],
        [F],
        [T]
    ]
    return X, Y
    
def or_data():
    # 학습 데이터
    X = [
        [F, F, B], # F
        [F, T, B], # T
        [T, F, B], # T
        [T, T, B], # T
    ]
    # 학습 데이터에 따른 실제값
    Y = [
        [F],
        [T],
        [T],
        [T]
    ]
    return X, Y
    
def xor_data():
    # 학습 데이터
    X = [
        [F, F, B], # F
        [F, T, B], # T
        [T, F, B], # T
        [T, T, B], # F
    ]
    # 학습 데이터에 따른 실제값
    Y = [
        [F],
        [T],
        [T],
        [F]
    ]
    return X, Y

In [4]:
# and 연산에 필요한 데이터를 호출한다.
# X, Y = and_data()
# or 연산에 필요한 데이터를 호출한다.
# X, Y = or_data()
# xor 연산에 필요한 데이터를 호출한다.
X, Y = xor_data()
print(X, Y)

[[0.0, 0.0, 1.0], [0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 1.0]] [[0.0], [1.0], [1.0], [0.0]]


tensorflow를 사용해서 퍼셉트론을 구현한다.

논리 연산을 위한 입력값으로 X, Y, 바이어스를 입력받아(총 3개의 입력) 1개의 값을 출력해야 하므로 가중치는 [3, 1]로 설정한다.

In [5]:
# W = tf.Variable(tf.random_normal([3, 1], dtype=tf.float32)) # 정규 분포를 따르는 난수를 만든다.
W = tf.Variable(tf.random_uniform([3, 1], dtype=tf.float32)) # 균등 분포를 따르는 난수를 만든다.
sess = tf.Session() # 세션을 만든다.
sess.run(tf.global_variables_initializer()) # 변수를 초기화 한다.
print(sess.run(W))

[[0.6162323 ]
 [0.5779532 ]
 [0.92657137]]


퍼셉트론은 두 개의 입력이 있을 때 하나의 뉴런으로 두 개의 입력을 계산한뒤 최종적으로 0 또는 1을 출력한다.  
두 개의 입력은 가중치와 곱해져서 뉴런의 첫 번째 단계인 시그마로 들어가고 시그마 단계에서 가중치와 입력값을 곱한 결과에 바이어스를 더하는 과정이 이루어진다.  
시그마 값은 뉴런의 두 번째 단계인 활성화 함수의 입력으로 들어가는데 퍼셉트론은 스텝 함수라는 활성화 함수를 사용하고 스텝 함수는 시그마 값이 <= 0일 경우 0을 시그마 값이 > 0일 경우 1을 출력한다.

In [6]:
# tensorflow의 greater(a, b) 메소드는 a > b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.greater(1, 0)))
# tensorflow의 greater_equal(a, b) 메소드는 a >= b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.greater_equal(1, 0)))
# tensorflow의 less(a, b) 메소드는 a < b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.less(1, 0)))
# tensorflow의 less_equal(a, b) 메소드는 a <= b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.less_equal(1, 0)))
# tensorflow의 equal(a, b) 메소드는 a == b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.equal(1, 0)))
# tensorflow의 not_equal(a, b) 메소드는 a != b일 경우 True, 그렇치않으면 False를 리턴한다.
print(sess.run(tf.not_equal(1, 0)))

True
True
False
False
False
True


In [7]:
# tensorflow의 cast(데이터, dtype) 메소드는 데이터를 dtype으로 형변환시킨다.
# True를 숫자로 형변환시키면 1로 False를 숫자로 형변환시키면 0으로 변환한다.
print(sess.run(tf.greater(1, 0)))
print(sess.run(tf.cast(tf.greater(1, 0), dtype=tf.float32)))
print(sess.run(tf.greater(1, 1)))
print(sess.run(tf.cast(tf.greater(1, 1), dtype=tf.float32)))

True
1.0
False
0.0


활성화 함수를 만든다.

In [8]:
# 함수의 인수로 전달받은 데이터가 0보다 크면 1을 그렇치않으면 0을 리턴하는 함수
def step(x):
    return tf.cast(tf.greater(x, 0), dtype=tf.float32)

In [9]:
print(sess.run(step(1)))
print(sess.run(step(0)))

1.0
0.0


오차(비용) 함수로 평균 제곱 오차(MSE)를 사용한다.

In [10]:
# 예측값을 계산하기 위해서 행렬의 내적 메소드로 학습 데이터(X)와 가중치(W)를 내적한다.
Z = tf.matmul(X, W)
print('예측값\n', sess.run(Z), sep='')
print('=' * 100)

# 예측값을 활성화 함수에 넣어서 최종 예측값을 계산한다.
result = step(Z)
print('최종 예측값\n', sess.run(result), sep='')
print('=' * 100)

# 레이블(Y)과 최종 예측값(활성화 함수 실행 결과, result)의 편차를 계산한다.
error = tf.subtract(Y, result)
print('레이블과 최종 예측값의 편차\n', sess.run(error), sep='')
print('=' * 100)

mse = tf.reduce_mean(tf.square(error))
print('평균 제곱 오차\n', sess.run(mse), sep='')

예측값
[[0.92657137]
 [1.5045246 ]
 [1.5428036 ]
 [2.1207569 ]]
최종 예측값
[[1.]
 [1.]
 [1.]
 [1.]]
레이블과 최종 예측값의 편차
[[-1.]
 [ 0.]
 [ 0.]
 [-1.]]
평균 제곱 오차
0.5


보통의 경우 딥러닝 모델은 경사 하강법을 통해 매개 변수를 최적화하지만 미분값이 큰 영향이 없는 스텝 함수의 영향으로(0은 미분 불가능, 1(상수)은 미분하면 1) 퍼셉트론은 아래와 같은 방법으로 최적화를 진행한다.

퍼셉트론 오차  
결과 값이 1이 나와야하는데 스텝 함수의 출력이 0일 경우: new_w = old_w + delta  
결과 값이 0이 나와야하는데 스텝 함수의 출력이 1일 경우: new_w = old_w - delda

위의 2가지 경우를 다음과 같이 사용할 수 있다.

In [11]:
print(X)
print(type(np.array(X)))
print(np.array(X))
print(np.array(X).T) # 전치

[[0.0, 0.0, 1.0], [0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 1.0]]
<class 'numpy.ndarray'>
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]]


matmul(A, B, transpose_a=True)는 행렬을 내적하기 전에 A 행렬을 전치하고 내적한다.  
matmul(A, B, transpose_b=True)는 행렬을 내적하기 전에 B 행렬을 전치하고 내적한다.  

In [12]:
delta = tf.matmul(X, error, transpose_a=True) # 행렬의 내적을 계산하지 전에 행렬 X를 내적한다.
print('가중치를 수정할 값\n', sess.run(delta), sep='')
print('=' * 100)

# 가중치를 가중치를 수정할 값으로 수정해서 다시 퍼셉트론을 계산한다. => 역전파
print('수정된 가중치\n', sess.run(tf.add(W, delta)), sep='')
# assign() 메소드는 세션 내부에서 tenserflow 변수에 저장된 값을 수정한다.
train = tf.assign(W, tf.add(W, delta))

가중치를 수정할 값
[[-1.]
 [-1.]
 [-2.]]
수정된 가중치
[[-0.38376772]
 [-0.42204678]
 [-1.0734286 ]]


학습 후 테스트

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

err, epoch, max_epoch = 1.0, 0, 20 # 오차, 현재 학습 횟수, 최대 학습 횟수
# 오차가 발행하고 현재 학습 횟수가 최대 학습 횟수를 넘어가지 않는 동안 반복한다.
while err > 0.0 and epoch < max_epoch:
    epoch += 1 # 학습 횟수를 증가시킨다.
    err = sess.run(mse) # 평균 제곱 오차를 계산한다.
    sess.run(train) # 학습시킨다.
    print('epoch: {:2d}, mse: {}'.format(epoch, err))

print('=' * 100)
print('학습 결과\n', sess.run(result))

epoch:  1, mse: 0.5
epoch:  2, mse: 0.5
epoch:  3, mse: 0.5
epoch:  4, mse: 0.5
epoch:  5, mse: 0.5
epoch:  6, mse: 0.5
epoch:  7, mse: 0.5
epoch:  8, mse: 0.5
epoch:  9, mse: 0.5
epoch: 10, mse: 0.5
epoch: 11, mse: 0.5
epoch: 12, mse: 0.5
epoch: 13, mse: 0.5
epoch: 14, mse: 0.5
epoch: 15, mse: 0.5
epoch: 16, mse: 0.5
epoch: 17, mse: 0.5
epoch: 18, mse: 0.5
epoch: 19, mse: 0.5
epoch: 20, mse: 0.5
학습 결과
 [[1.]
 [1.]
 [1.]
 [1.]]


In [14]:
# 세션을 with 구문을 사용해서 만들면 with 블록이 종료되는 순간 자동으로 세션이 close 된다.
with tf.Session() as sess: # 세션을 만든다.
    sess.run(tf.global_variables_initializer())
    err, epoch, max_epoch = 1.0, 0, 20
    while err > 0.0 and epoch < max_epoch:
        epoch += 1
        err = sess.run(mse)
        sess.run(train)
        print('epoch: {:2d}, mse: {}'.format(epoch, err))

    print('=' * 100)
    print('학습 결과\n', sess.run(result))
# ===== with

epoch:  1, mse: 0.5
epoch:  2, mse: 0.5
epoch:  3, mse: 0.5
epoch:  4, mse: 0.5
epoch:  5, mse: 0.5
epoch:  6, mse: 0.5
epoch:  7, mse: 0.5
epoch:  8, mse: 0.5
epoch:  9, mse: 0.5
epoch: 10, mse: 0.5
epoch: 11, mse: 0.5
epoch: 12, mse: 0.5
epoch: 13, mse: 0.5
epoch: 14, mse: 0.5
epoch: 15, mse: 0.5
epoch: 16, mse: 0.5
epoch: 17, mse: 0.5
epoch: 18, mse: 0.5
epoch: 19, mse: 0.5
epoch: 20, mse: 0.5
학습 결과
 [[1.]
 [1.]
 [1.]
 [1.]]
